name = "xtalk"
main = "../../build/worker/shim.mjs"
compatibility_date = "2024-09-23"

[build]
command = "cargo install -q worker-build && worker-build --release --features worker"
cwd = "../.."

[vars]
BASE_URL = "https://xtalk.raw2.cc"
TOKEN_CACHE_TTL = "3600"

[[d1_databases]]
binding = "DB"
database_name = "xtalk-db"
database_id = "f34f0fb2-dd07-49a2-8073-4bdaf3cb02e4"
